---
api_version: catalog/v1
type: Integration
metadata:
  namespace: ansible
  name: ansible-tower-remediation
spec:
  class: community # community, supported, enterprise, or partner
  provider: remediation # backend, backend/alert, backend/incidents, backend/metrics, backend/events, backend/deregistration, backend/remediation, or backend/other
  short_description: Ansible Tower Remediation
  tags:
  - ansible
  - remediation
  - self healing
  - automation
  contributors:
  - "@sensu"
  - "@calebhailey"
  - "@jspaleta"
