---
api_version: catalog/v1
type: Integration
metadata:
  namespace: ansible
  name: ansible-tower-remediation
spec:
  class: community
  provider: remediation
  display_name: Ansible Tower
  short_description: Triggers Ansible Tower job templates for automated remediation.
  tags:
    - ansible
    - remediation
    - self healing
    - automation
  contributors:
    - "@sensu"
    - "@calebhailey"
    - "@jspaleta"
  prompts:
    - type: section
      title: Mattermost Secrets
    - type: markdown
      body: |
        This integration requires a Ansible Tower API URL and API Token for API Authentication.

        Please visit [Ansible Tower API OAuth Guide] for more information.

        [Ansible Tower OAuth Guide]: https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html
    - type: section
      title: Ansible Tower API URL
    - type: question
      name: api_url_secret_provider
      input:
        type: string
        title: Ansible Tower API URL Secret Provider
        description: >-
          Select the API URL secret provider where the secrets is stored
        enum:
          - env
          - vault
        default: env
    - type: question
      name: api_url_secret_id
      input:
        type: string
        title: Ansible Tower API URL Secret ID
        description: >-
          Provide the API URL secret identifier (i.e. environment variable name, or Vault secret key/path)
        default: SENSU_ANSIBLE_TOWER_HOST
    - type: section
      title: Ansible Tower API Token
    - type: question
      name: api_token_secret_provider
      input:
        type: string
        title: API Token Secret Provider
        description: >-
          Select the API Token secret provider where the secrets is stored
        enum:
          - env
          - vault
        default: env
    - type: question
      name: api_token_secret_id
      input:
        type: string
        title: Secret ID
        description: >-
          Provide the API Token secret identifier (i.e. environment variable name, or Vault secret key/path)
        default: SENSU_ANSIBLE_TOWER_TOKEN
  resource_patches:
    - resource:
        api_version: secrets/v1
        type: Secret
        name: ansible_tower_host
      patches:
        - path: /spec/provider
          op: replace
          value: "[[api_url_secret_provider]]"
        - path: /spec/id
          op: replace
          value: "[[api_url_secret_id]]"
    - resource:
        api_version: secrets/v1
        type: Secret
        name: ansible_tower_token
      patches:
        - path: /spec/provider
          op: replace
          value: "[[api_token_secret_provider]]"
        - path: /spec/id
          op: replace
          value: "[[api_token_secret_id]]"
