---
api_version: catalog/v1
type: Integration
metadata:
  namespace: ansible
  name: ansible-tower-remediation
spec:
  class: community
  provider: remediation
  short_description: Ansible Tower Remediation
  tags:
  - ansible
  - remediation
  - self healing
  - automation
  contributors:
  - "@sensu"
  - "@calebhailey"
  - "@jspaleta"
