---
name: 'Sensu Catalog Workflow'
on: [push, pull_request]
env:
  catalog_api_version: 0.1.0-alpha.10

jobs:
  validate:
    name: 'Validate Sensu Catalog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # The whole repository must be cloned
      - name: Run Sensu Catalog validation
        uses: ./.github/actions/validate-catalog
        with:
          catalog-api-version: ${{ env.catalog_api_version }}

  generate:
    name: 'Generate Sensu Catalog API'
    runs-on: ubuntu-latest
    if: contains(fromJson('["push", "create"]'), github.event_name) && contains(github.ref, 'refs/tags/')
    needs: validate
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # The whole repository must be cloned
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.generate-api.outputs.release-dir }}
          key: generated-catalog-api
      - name: Run Sensu Catalog API generation
        uses: ./.github/actions/generate-catalog-api
        id: generate-api
        with:
          catalog-api-version: ${{ env.catalog_api_version }}

  publish:
    name: 'Publish Sensu Catalog API'
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.generate-api.outputs.release-dir }}
          key: generated-catalog-api
      - name: Run Sensu Catalog API publisher
        uses: ./.github/actions/publish-catalog-api
        with:
          release-dir: ${{ steps.generate-api.outputs.release-dir }}
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
