---
name: 'Sensu Catalog Workflow (Staging)'

on:
  push:
    branches:
      - '**'

jobs:
  staging:
    uses: ./.github/workflows/sensu-catalog.yml
    with:
      catalog_snapshot: true
    secrets:
      aws_s3_bucket: ${{ secrets.STAGING_AWS_S3_BUCKET }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
